### ISSUE TITLE
Is the website being redeployed?

### ISSUE THREAD

**Issue by Kobzol** [mre/idiomatic-rust#50]
Hi, I clicked on the "Are out parameters idiomatic in Rust?" article and noticed that it has a broken link. Then I saw that it has been fixed two months ago (https://github.com/mre/idiomatic-rust/commit/6de41c9c59978fd91349c731894f684696777c97), but apparently that fix didn't get to idiomatic.rs (?).

**Comment by mre** [comment]
Oh, good point. It's not automatically deployed at the moment. In the past, there were not that many changes to the list, which is why I didn't automate the process yet.
I've updated the idiomatic.rs website now.

While I was at it, I slightly simplified the process, such that I only have to copy the `resources.json` file over to my other project and it will work.
https://github.com/corrode/corrode.github.io/commit/f39f4167df9cc8c62cd623afaffe3da3919123c2
In the past, I needed to do some post-processing by mangling the data for `DataTables`. 
The way to fully automate the process would be to fetch the latest `resources.json` as part of the CI/CD process of the repo. I might do that in the future.

Thanks a lot for opening the issue.
